tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: BSA_ROLE
      database: bsa_dbt
      schema: DEV
      warehouse: BERT_WH
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: BSA_ROLE
      database: bsa_dbt
      schema: PROD
      warehouse: BERT_WH